//! AWS KMS root of trust, using the envelope primitive rather than direct encryption.
//!
//! `GenerateDataKey` returns the data key twice — in clear, and sealed under the CMK. That
//! is precisely the envelope, provided by the service. Keycast instead calls `Encrypt` on
//! the payload itself, paying a KMS round trip per secret and per load.
//!
//! Block D2 changes nothing here: the CMK policy gains
//! `kms:RecipientAttestation:ImageSha384`, and this code is untouched. That property is the
//! reason the trait exists at all.

use aws_sdk_kms::Client;
use aws_sdk_kms::primitives::Blob;
use aws_sdk_kms::types::DataKeySpec;
use nostr_remote_signer_core::{KeyUnwrapError, KeyUnwrapper, UnwrapFuture};
use zeroize::Zeroizing;

#[derive(Debug)]
pub struct KmsUnwrapper {
    client: Client,
    key_id: String,
}

impl KmsUnwrapper {
    pub async fn from_env() -> Result<Self, KeyUnwrapError> {
        let key_id = std::env::var("BUNKER_KMS_KEY_ID")
            .map_err(|_| KeyUnwrapError::Configuration("BUNKER_KMS_KEY_ID is not set".into()))?;
        let config = aws_config::load_from_env().await;
        Ok(Self {
            client: Client::new(&config),
            key_id,
        })
    }

    /// Ask KMS for a fresh data key. Returns (plaintext, sealed) — the envelope, in one call.
    ///
    /// This is NOT `wrap_data_key`: with KMS the data key is generated BY the service, so
    /// sealing can skip the separate `Encrypt` round trip entirely. Keeping it off the trait
    /// is deliberate — a passphrase backend has no equivalent, and widening the trait to fit
    /// one backend would be exactly the mistake Keycast's `KeyManager` makes.
    pub async fn generate_data_key(&self) -> Result<(Zeroizing<Vec<u8>>, Vec<u8>), KeyUnwrapError> {
        let out = self
            .client
            .generate_data_key()
            .key_id(&self.key_id)
            .key_spec(DataKeySpec::Aes256)
            .send()
            .await
            .map_err(|e| KeyUnwrapError::Backend(e.to_string()))?;

        let plaintext = out
            .plaintext()
            .ok_or_else(|| KeyUnwrapError::Backend("KMS returned no plaintext".into()))?;
        let sealed = out
            .ciphertext_blob()
            .ok_or_else(|| KeyUnwrapError::Backend("KMS returned no ciphertext".into()))?;

        Ok((
            Zeroizing::new(plaintext.as_ref().to_vec()),
            sealed.as_ref().to_vec(),
        ))
    }
}

impl KeyUnwrapper for KmsUnwrapper {
    fn wrap_data_key<'a>(&'a self, data_key: &'a [u8]) -> UnwrapFuture<'a, Vec<u8>> {
        Box::pin(async move {
            let out = self
                .client
                .encrypt()
                .key_id(&self.key_id)
                .plaintext(Blob::new(data_key))
                .send()
                .await
                .map_err(|e| KeyUnwrapError::Backend(e.to_string()))?;

            out.ciphertext_blob()
                .map(|b| b.as_ref().to_vec())
                .ok_or_else(|| KeyUnwrapError::Backend("KMS returned no ciphertext".into()))
        })
    }

    fn unwrap_data_key<'a>(&'a self, wrapped: &'a [u8]) -> UnwrapFuture<'a, Zeroizing<Vec<u8>>> {
        Box::pin(async move {
            let out = self
                .client
                .decrypt()
                .key_id(&self.key_id)
                .ciphertext_blob(Blob::new(wrapped))
                .send()
                .await
                .map_err(|e| KeyUnwrapError::Backend(e.to_string()))?;

            out.plaintext()
                .map(|b| Zeroizing::new(b.as_ref().to_vec()))
                .ok_or(KeyUnwrapError::Invalid)
        })
    }

    fn name(&self) -> &'static str {
        "aws-kms"
    }
}
